spring.application.name=phishing-detection

spring.datasource.url=jdbc:postgresql://localhost:5432/phishing_detection_db
spring.datasource.username=akshatmehta
spring.datasource.password=
server.port=8092
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true