spring.application.name=phishing-detection

spring.datasource.url=jdbc:postgresql://localhost:5432/phishing_detection_db
spring.datasource.username=your_username
spring.datasource.password=your_password
server.port=8080
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#VirusTotal Integration
virustotal.api.key=${VIRUSTOTAL_API_KEY}
virustotal.api.url=https://www.virustotal.com/api/v3